14_OMG/config/routes.rb
WBlog::Application.routes.draw do
  root :to => 'blogs#index'

  resources :blogs, :only=>[:index, :show, :edit] do
    collection do
      get :rss
    end
    resources :comments, only: [:index, :create]
    resources :likes, only: [:index, :create, :destroy] do
      member do
        get :is_liked
      end
    end
  end


  resources :archives
  resources :subscribes do
    collection do
      post :cancel
    end
  end
  get '/unsubscribe' => 'subscribes#index'
  # photos
  resources :photos, only: [:create]
  get '/qrcodes' => 'qrcodes#show'
  
  namespace :admin do
    resources :posts do
      collection do
        post :preview
      end
      resources :comments
    end
    resources :sessions, :only=>[:new, :create, :destroy]
    root to: 'dashboard#index'
  end

  get '/about' => 'home#index'
  get '/mobile' => 'home#mobile'
  get '/:type' => 'archives#index', constraints: { type: /tech|life|creator/ }
end

14_OMG/app/models/post.rb
# encoding : utf-8
#
require 'markdown'
class Post
  TECH = "技术"
  LIFE = "生活"
  CREATOR = "创业"
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Pagination
  field :title, :type => String
  field :content, :type => String
  field :type, :type=> String
  field :visited_count, :type=>Integer, :default=>0

  has_many :comments
  has_and_belongs_to_many :labels

  has_many :likes

  validates :title, :presence=>true, :uniqueness=> true
  validates :content, :presence=>true, :length => { :minimum=> 30 }
  validates :type, :presence=>true, :inclusion => { :in => [ TECH, LIFE, CREATOR ] }

  after_create do
    if ENV['MAIL_SERVER'].present?
      NewPostWorker.perform_async(self.id.to_s)
    end
  end

  def content_html
    self.class.render_html(self.content)
  end

  def self.render_html(content)
    rd = CodeHTML.new
    md = Redcarpet::Markdown.new(rd, autolink: true, fenced_code_blocks: true)
    md.render(content)
  end

  def type_en
    map = {
      '技术' => 'Tech',
      '生活' => 'Life',
      '创业' => 'Creator',
    }

    if I18n.locale == :en
      map[type]
    else
      type
    end
  end

  def visited
    self.visited_count += 1
    self.save
    self.visited_count
  end

  # 显示给首页截断数据
  def sub_content
    HTML_Truncator.truncate(content_html, 300, length_in_chars: true)
  end

  # 显示给 meta description
  def meta_content
    html = HTML_Truncator.truncate(content_html, 100, :length_in_chars => true, ellipsis: '')
    # 加上 div 以方便 Nokogiri 获取 text()
    html = '<div>' + html + '</div>'
    Nokogiri.parse(html).text()
  end

  def labels_content( need_blank=false )
    content = self.labels.collect { |label| label.name }.join(", ")
    content = I18n.t('none') if content.blank? and !need_blank
    content
  end

  def liked_count
    self.likes.size
  end
end

14_OMG/app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  layout 'layouts/admin'
  before_action :authericate_user!

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find( params[:id] )
  end

  def show
    post = Post.find( params[:id] )
    render :json=> {
      title: post.title,
      type: post.type,
      labels: post.labels_content(true),
      content: post.content
    }
  end

  def destroy
    @post = Post.find( params[:id] )
    if @post.destroy
      flash[:notice] = '删除博客成功'
      redirect_to admin_posts_path
    else
      flash[:error] = '删除博客失败'
      redirect_to admin_posts_path
    end
  end

  def index
    @posts = Post.desc(:created_at)
  end

  def create
    labels = params.delete(:labels).to_s
    @post = Post.new( params.permit(:title, :content, :type) )
    initialize_or_create_labels(labels)

    if @post.save
      flash[:notice] = '创建博客成功'
      redirect_to admin_posts_path
    else
      flash.now[:error] = '创建失败'
      render :new
    end
  end

  def update
    @post = Post.find( params[:id] )

    labels = params.delete(:labels).to_s
    initialize_or_create_labels(labels)

    if @post.update( params.permit(:title, :content, :type) )
      flash[:notice] = '更新博客成功'
      redirect_to admin_posts_path
    else
      flash[:error] = '更新博客失败'
      render :edit
    end
  end

  def preview
    render plain: Post.render_html(params[:content] || "")
  end

  private
  def initialize_or_create_labels(labels)
    @post.labels = []
    labels.split(",").each do |name|
      label = Label.find_or_initialize_by(name: name.strip)
      label.save!
      @post.labels << label
    end
  end
end

14_OMG/app/views/admin/posts/_form.html.slim
- url = @post.new_record? ? admin_posts_path : admin_post_path(@post)
= simple_form_for(@post, url: url, html: {novalidate: '' }) do |f|
  .row
    .large-6.columns
      = f.input :title, label: t('admin.posts_attributes.title'), "ng-model"=>"title", input_html: { name: 'title' }
  .row
    .small-6.large-3.columns
      = f.input :type, :as=>:select, :collection=> [ Post::TECH, Post::LIFE, Post::CREATOR ], label: t('admin.posts_attributes.type'), "ng-model"=>"type", input_html: { name: 'type' }
  .row
    .small-12.large-6.columns
      = label_tag :labels, t('admin.posts_attributes.labels')
      = text_field_tag :labels, @post.labels_content(true), "ng-model"=>"labels", "ng-initial" => ''

  .row
    .small-12.columns
      p
        | #{t('admin.posts_attributes.already_labels')}
        span
          - Label.all.each do |label|
            a.tag href="#" ng-click="addTag($event)" #{label.name}

  / tabs and upload file field
  dl.tabs
    dd ng-class="{ active: body_active }"
      a href="" ng-click="changeToBody()" #{t('admin.posts_attributes.content')}
    dd ng-class="{ active: !body_active }"
      a href="#" ng-click="changeToPreview()" #{t('admin.posts_attributes.preview')}
    = link_to t('admin.posts_attributes.upload_photo'), "#", :id=>'upload_photo'
  input[type="file" style="display: none;"]

  .content-field ng-show="body_active" ng-model= 'content'
    = f.input :content, :as=> :text, :label => false, input_html: { name: 'content', "ng-model"=>'content', 'ng-initial'=>'' }

  .preview.markdown ng-hide="body_active" ng-bind-html=" trustAsPreviewHTML() "

  .row
    .small-12.large-6.columns.posts-button
      button #{t('admin.posts_attributes.submit')}

14_OMG/app/views/admin/posts/edit.html.slim
.row
  .small-12.columns
    .admin-posts-field ng-controller="AdminPostsController" ng-init="init('#{@post.id}')" 
      h3.blog-title 修改博客
      = render 'form'

14_OMG/app/views/admin/posts/index.html.slim
.row.admin-posts-field
  .small-12.columns
    h3.blog-title #{t('admin.posts') }
    table width="100%"
      thead
        tr
          th #{t('admin.posts_head.title')}
          th #{t('admin.posts_head.summary')}
          th #{t('admin.posts_head.operation')}
      tbody
        - @posts.each do |post|
          tr
            td
              = link_to post.title, blog_path(post)
            td.admin-post-summary-field
              i.fi-calendar
              span #{format_time(post.created_at)}
              i.fi-list
              span #{ post.type_en }
              i.fi-pricetag-multiple
              span #{ post.labels_content }
              i.fi-torsos
              span #{ post.visited_count }
              i.fi-heart
              span #{ post.liked_count }
            td
              = link_to t('comment'), admin_post_comments_path(post.id), class: 'edit-post-link'
              = link_to t('edit'), edit_admin_post_path(post), class: 'edit-post-link'
              = link_to t('destroy'), admin_post_path(post), method: 'DELETE', 'data-confirm' => '确认删除?'

14_OMG/app/views/admin/posts/new.html.slim
.row
  .small-12.columns
    .admin-posts-field ng-controller="AdminPostsController"
      h3.blog-title #{t('admin.new_post')}
      = render 'form'