2_BMShark_身边网/config/routes.rb
Rails.application.routes.draw do

  
  resources :sessions, only:[:new, :create, :destroy]
	match '/signup', to: 'users#new' ,via: 'get'
	match '/signin', to: 'sessions#new', via: 'get'
	match '/signout', to: 'sessions#destroy', via: 'delete'
  root to: 'static_pages#home'

  match '/about', to: 'static_pages#about', via: 'get'
  
  resources :shops
  resources :admins
  resources :products
  resources :users
  

end

2_BMShark_身边网/app/views/layouts/_footer.html.erb
<footer class="footer">
<nav>
<ul>
<li><%= link_to "关于", about_path %></li>
</ul>
</nav>
</footer>

2_BMShark_身边网/app/views/layouts/_header.html.erb
<header class="header navbar navbar-fixed-top navbar-inverse">
<div class="navbar-inner">
		<div class="container">
				<%= link_to "身边网",'/', id: "logo" %>
			<nav>
				<ul class="nav pull-right">
				<li><%= link_to "商店", shops_path %></li>
				<% if signed_in? %>
					<li id="fat-menu" class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						用户 <b class="caret"></b>
					</a>
					<ul class="dropdown-menu">
						<li><%= link_to "用户页面", current_user %></li>
						<li><%= link_to "用户设置", edit_user_path(current_user) %></li>
						<li class="divider"></li>
						<li>
						<%= link_to "登出", signout_path, method: "delete" %>
						</li>
					</ul>
					</li>
				<% else %>
					<li><%= link_to "登陆", signin_path %></li>
				<% end %>
				</ul>
			</nav>
		</div>
		</div>
</header>

2_BMShark_身边网/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

2_BMShark_身边网/app/views/layouts/application.html.erb
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<%= render 'layouts/header' %>
<body>
	<div class="container">
		<% flash.each do |key, value| %>
		<div class="alert alert-<%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>