7_gkmb2/config/routes.rb
RailsForum::Application.routes.draw do

    resources :resumes, only: [:index, :new, :create, :destroy]

    concern   :user_comments,  TheComments::UserRoutes.new
    concern   :admin_comments, TheComments::AdminRoutes.new
    resources :comments, concerns:  [:user_comments, :admin_comments]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
    devise_for :users, :controllers => { :registrations => :registrations, :confirmations => :confirmations }
    get 'user/:id', to: 'users#show', as: 'user'

    resources :categories do
        resources :topics do
            resources :posts

        end
    end

    get 'home/confirm', to: 'home#confirm', as: 'home_confirm'
    get 'home/thanks', to: 'home#thanks', as: 'home_thanks'

    root :to => "categories#index"

  

end

7_gkmb2/app/models/category.rb
class Category < ActiveRecord::Base
    has_many :topics, :dependent => :destroy

    validates :title, presence: true, length: { minimum: 1 }
    has_attached_file :image, styles: { medium: "100000x100000>", thumb: "50x50>" }
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

7_gkmb2/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    skip_before_filter :authenticate_user!, :only => [:index, :show]
    skip_before_filter :authenticate_admin!, :only => [:index, :show]

    def index
        @cats = Category.all
        # @cats = Category.all.order("created_at DESC")
    end

    def new
        @cat = Category.new
    end

    def create
        @cat = Category.new(category_permit)
        @cat.last_activity_at = Time.now
        if @cat.save
            flash[:success] = "A new category was created."
            redirect_to root_path
        else
            render 'new'
        end
    end

    def show
        @cat = Category.find(params[:id])
        @all_topics = @cat.topics.order('created_at desc').order('last_activity_at desc')
        @topics = @all_topics.page(params[:page]).per(10)
    end

    def edit
        @cat = Category.find(params[:id])
    end 

    def update
        @cat = Category.find(params[:id])
        if @cat.update(category_permit)
            flash[:info] = "The category was updated."
            redirect_to @cat
        else
            render 'edit'
        end
    end

    def destroy
        @cat = Category.find(params[:id])
        @cat.destroy

        flash[:info] = "The category was deleted."
        redirect_to categories_path
    end

    private

    def category_permit
        params[:category].permit(:title, :description,:image)
    end
end

7_gkmb2/app/helpers/categories_helper.rb
module CategoriesHelper
end

7_gkmb2/app/views/categories/_form.html.erb
<%= form_for @cat,:html => { :class => 'form-horizontal', :role => "form" } do |f| %>
    <%= render 'partials/form_errors', :obj => @cat, :name => :category %>
    <div class="form-group">
        <%= f.label :title, :class => "col-lg-2 col-md-2 col-sm-2 control-label" %>
        <div class="col-lg-10 col-md-10 col-sm-10">
            <%= f.text_field :title, :class => "form-control", :placeholder => "Title" %>
        </div>
    </div>

    <div class="form-group">
      <%= f.file_field :image , :class => "col-lg-2 col-md-2 col-sm-2 control-label"%>
    </div>
    <div class="form-group">
        <%= f.label :description, :class => "col-lg-2 col-md-2 col-sm-2 control-label" %>
        <div class="col-lg-10 col-md-10 col-sm-10">
            <%= f.text_area :description, :class => "form-control", :placeholder => "Description" %>
        </div>
    </div>
    <div class="form-group">
        <div class="col-lg-offset-2 col-md-offset-2 col-sm-offset-2 col-lg-10 col-md-10 col-sm-10">
            <% if ['new', 'create'].include? params[:action] %>
                <button type="submit" class="btn btn-primary">Create Category</button>
            <% elsif ['edit', 'update'].include? params[:action] %>
                <button type="submit" class="btn btn-primary">Edit Category</button>
            <% end %>
            <%= link_to "Cancel", :back, :class => "btn btn-default" %>
        </div>
    </div>
<% end %>

7_gkmb2/app/views/categories/_show_actions_block.html.erb
<div class="actions-block clearfix">
    <div class="pull-left" style="margin-bottom: 20px">
        <%= link_to "创建子话题", [:new, @cat, :topic], :class => 'btn btn-default' %>
        <% if @is_owner || @is_admin %>
            <%= link_to "Edit Category", [:edit, @cat], :class => 'btn btn-default' %>
        <% end %>
        <% if @is_admin %>
            <%= link_to "Delete Category", @cat, method: :delete, :data => { :confirm => "Are you sure?" }, :class => 'btn btn-danger' %>
        <% end %>
    </div>
    <%= render 'partials/pagination', :all => @all_topics, :some => @topics, :name => :topic, :classes => 'pull-right' %>
</div>

7_gkmb2/app/views/categories/edit.html.erb
<div class="page-header">
    <h1>Edit Category</h1>
</div>
<%= render 'form' %>

7_gkmb2/app/views/categories/index.html.erb
<br>
<%= render 'partials/alerts' %>

<br>
<ol class="breadcrumb">
  <li class="active">话题
</ol>

<% if @is_admin %>
    <%= link_to "New Category", new_category_path, :class => 'btn btn-default', :style => 'margin-bottom: 20px' %>
<% end %>



<% @cats.each do |cat| %>
    <div class="col text-center" style="align: center">
      <div class="col-sm-2">
        <div class="thumbnail">
          <a href="<%= url_for(category_path(cat)) %>"> <%= image_tag(cat.image.url(:medium)) %></a>

           <%= cat.description%>
          <br>
          <%= link_to cat.title, category_path(cat) , class: "btn btn-success"%>
        </div>
      </div>
    </div>
<% end %>
<br>
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>


  <title>Bootstrap Example</title>
  <meta charset="utf-8">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!--<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">-->
  <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>-->
  <!--<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>-->

<style>
      .carousel-inner > .item > img,
      .carousel-inner > .item > a > img {
          width: 100%;
          margin:0em;

      }
  </style>


<div class="container">
  <br>
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
      <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <img src="b5.jpg" alt="a" width="260" height="60">
      </div>

      <div class="item">
        <img src="b6.jpg" alt="b" width="260" height="60">
      </div>

      <div class="item">
        <img src="b9.jpg" alt="c" width="260" height="60">
      </div>

      <div class="item">
        <img src="b7.jpg" alt="d" width="260" height=60">
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div>
  <br>
  <br>  <br>
  <br>
  <br>








<table class="hidden">
  <tr>
    <th></th>
    <th>话题</th>
    <th>描述</th>
    <th>子话题</th>
    <th>最近活跃</th>
  </tr>
  <% @cats.each_with_index do |cat, x| %>
      <tr>
        <td><%= x + 1 %></td>
        <td><%= link_to cat.title, category_path(cat) %></td>
        <td><%= cat.description %></td>
        <td><%= cat.topics.count %></td>
        <td>
          <%= time_ago_in_words cat.last_activity_at %>
          <% if cat.last_activity_user_id
               user = User.find(cat.last_activity_user_id) %> ago
              by <%= link_to user.display_name, user_path(user) %>
          <% end %>
        </td>
      </tr>
  <% end %>
</table>

7_gkmb2/app/views/categories/new.html.erb
<div class="page-header">
    <h1>New Category</h1>
</div>
<%= render 'form' %>

7_gkmb2/app/views/categories/show.html.erb
<br>
<%= render 'partials/alerts' %>

<ol class="breadcrumb">
    <li><%= link_to "目录", categories_path %>
    <li class="active"><%= @cat.title %>
</ol>
<div style="margin-bottom: 20px;">
    <% if @is_admin %>
    <% end %>
</div>

<% @topics.each do |topic| %>
    <div class="col text-center" style="align: center">


      <div class="col-sm-2">
        <div class="thumbnail">

          <a href="<%= url_for(category_topic_path(@cat,topic)) %>"> <%= image_tag(topic.image.url(:medium)) %></a>

           <%= topic.body%>
          <br>

          <%= link_to topic.title, [@cat, topic] , class: "btn btn-success"%>

        </div>
      </div>


    </div>
<% end %>
<table class="table">

    <tr>
         <th></th>
        <th>子话题</th>
        <th>帖子</th>
        <th>话题发起者</th>
        <th>创建</th>
        <th>最近活跃</th>
    </tr>


    <% @topics.each_with_index do |topic, x| %>
        <tr>

            <%
                user = User.find(topic.user_id)
                is_owner = user_signed_in? && current_user.id == user.id
            %>
            <td><%= x + 1 %></td>
            <td><%= link_to topic.title, [@cat, topic] %></td>
            <td><%= topic.posts.length %></td>
            <td><%= link_to user.display_name, user_path(user) %></td>
            <td><%= time_ago_in_words topic.created_at %> ago</td>
            <td>
                <%= time_ago_in_words topic.last_activity_at %> ago
                <% if topic.last_activity_user_id 
                    user = User.find(topic.last_activity_user_id) %>
                    by <%= link_to user.display_name, user_path(user) %>
                <% end %>
            </td>

        </tr>
    <% end %>

</table>
<%= render 'show_actions_block' %>