17_编程N次方_NthPower/config/routes.rb
Rails.application.routes.draw do
  resources :resumes, only: [:index, :new, :create, :destroy]
  
  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'resumes/index'

  get 'resumes/new'

  get 'resumes/create'

  get 'resumes/destroy'

  get 'sessions/new'
  get 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get 'static_pages/home'
  get 'static_pages/help'

  resources :rights
  resources :group_files
  resources :usergroups
  resources :groups
  resources :user_files
  resources :nthfiles
  resources :users
  

  root'static_pages#home'

end

17_编程N次方_NthPower/app/models/usergroup.rb
class Usergroup < ActiveRecord::Base
  has_many:users
  belongs_to:group
  has_many:nthfiles
end

17_编程N次方_NthPower/app/controllers/usergroups_controller.rb
class UsergroupsController < ApplicationController
  before_action :set_usergroup, only: [:show, :edit, :update, :destroy]

  # GET /usergroups
  # GET /usergroups.json
  def index
    @usergroups = Usergroup.all
  end

  # GET /usergroups/1
  # GET /usergroups/1.json
  def show
  end

  # GET /usergroups/new
  def new
    @usergroup = Usergroup.new
  end

  # GET /usergroups/1/edit
  def edit
  end

  # POST /usergroups
  # POST /usergroups.json
  def create
    @usergroup = Usergroup.new(usergroup_params)

    respond_to do |format|
      if @usergroup.save
        format.html { redirect_to @usergroup, notice: 'Usergroup was successfully created.' }
        format.json { render :show, status: :created, location: @usergroup }
      else
        format.html { render :new }
        format.json { render json: @usergroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usergroups/1
  # PATCH/PUT /usergroups/1.json
  def update
    respond_to do |format|
      if @usergroup.update(usergroup_params)
        format.html { redirect_to @usergroup, notice: 'Usergroup was successfully updated.' }
        format.json { render :show, status: :ok, location: @usergroup }
      else
        format.html { render :edit }
        format.json { render json: @usergroup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usergroups/1
  # DELETE /usergroups/1.json
  def destroy
    @usergroup.destroy
    respond_to do |format|
      format.html { redirect_to usergroups_url, notice: 'Usergroup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usergroup
      @usergroup = Usergroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usergroup_params
      params.require(:usergroup).permit(:user_id, :group_id, :diaplayname)
    end
end

17_编程N次方_NthPower/app/helpers/usergroups_helper.rb
module UsergroupsHelper
end

17_编程N次方_NthPower/app/views/usergroups/_form.html.erb
<%= form_for(@usergroup) do |f| %>
  <% if @usergroup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usergroup.errors.count, "error") %> prohibited this usergroup from being saved:</h2>

      <ul>
      <% @usergroup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :group_id %><br>
    <%= f.number_field :group_id %>
  </div>
  <div class="field">
    <%= f.label :diaplayname %><br>
    <%= f.text_field :diaplayname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

17_编程N次方_NthPower/app/views/usergroups/edit.html.erb
<h1>Editing Usergroup</h1>

<%= render 'form' %>

<%= link_to 'Show', @usergroup %> |
<%= link_to 'Back', usergroups_path %>

17_编程N次方_NthPower/app/views/usergroups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usergroups</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Group</th>
      <th>Diaplayname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usergroups.each do |usergroup| %>
      <tr>
        <td><%= usergroup.user_id %></td>
        <td><%= usergroup.group_id %></td>
        <td><%= usergroup.diaplayname %></td>
        <td><%= link_to 'Show', usergroup %></td>
        <td><%= link_to 'Edit', edit_usergroup_path(usergroup) %></td>
        <td><%= link_to 'Destroy', usergroup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usergroup', new_usergroup_path %>

17_编程N次方_NthPower/app/views/usergroups/new.html.erb
<h1>New Usergroup</h1>

<%= render 'form' %>

<%= link_to 'Back', usergroups_path %>

17_编程N次方_NthPower/app/views/usergroups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @usergroup.user_id %>
</p>

<p>
  <strong>Group:</strong>
  <%= @usergroup.group_id %>
</p>

<p>
  <strong>Diaplayname:</strong>
  <%= @usergroup.diaplayname %>
</p>

<%= link_to 'Edit', edit_usergroup_path(@usergroup) %> |
<%= link_to 'Back', usergroups_path %>